---
title: "SEC 2-FA1 GROUP 5-TOLENTINO, C."
author: "Charles Stephen Benedict R. Tolentino"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1: Skewness Formula Analysis

```{r}
# DATA LOADING & CLEANING

my_data <- read.csv("results.csv")
my_data[my_data == "NA"] <- NA
clean_data <- my_data

# Verify if columns load properly and check data

head(clean_data)

summary(clean_data)

# Set standard deviation for each exam subject

sd(clean_data$arch1, na.rm = TRUE)
sd(clean_data$prog1, na.rm = TRUE)
sd(clean_data$arch2, na.rm = TRUE)
sd(clean_data$prog2, na.rm = TRUE)

# Set mean, median, and standard deviation for Pearson Formula

m_arch1   <- mean(clean_data$arch1, na.rm = TRUE)
med_arch1 <- median(clean_data$arch1, na.rm = TRUE)
s_arch1   <- sd(clean_data$arch1, na.rm = TRUE)

m_arch2   <- mean(clean_data$arch2, na.rm = TRUE)
med_arch2 <- median(clean_data$arch2, na.rm = TRUE)
s_arch2   <- sd(clean_data$arch2, na.rm = TRUE)

m_prog1   <- mean(clean_data$prog1, na.rm = TRUE)
med_prog1 <- median(clean_data$prog1, na.rm = TRUE)
s_prog1   <- sd(clean_data$prog1, na.rm = TRUE)

m_prog2   <- mean(clean_data$prog2, na.rm = TRUE)
med_prog2 <- median(clean_data$prog2, na.rm = TRUE)
s_prog2   <- sd(clean_data$prog2, na.rm = TRUE)

# Run given and print Pearson's Formula

pearson_arch1 <- (3*(m_arch1 - med_arch1)) / s_arch1
pearson_arch1

pearson_arch2 <- (3*(m_arch2 - med_arch2)) / s_arch2
pearson_arch2

pearson_prog1 <- (3*(m_prog1 - med_prog1)) / s_prog1
pearson_prog1

pearson_prog2 <- (3*(m_prog2 - med_prog2)) / s_prog2
pearson_prog2

# Set values and determine exact skew based on equation 2.1

x <- na.omit(clean_data$arch1)
n <- length(x)
x_bar <- mean(x)
numerator <- sqrt(n) * sum((x - x_bar)^3)
denominator <- (sum((x - x_bar)^2))^(3/2)
exact_arch1 <- numerator / denominator
exact_arch1

x <- na.omit(clean_data$arch2)
n <- length(x)
x_bar <- mean(x)
numerator <- sqrt(n) * sum((x - x_bar)^3)
denominator <- (sum((x - x_bar)^2))^(3/2)
exact_arch2 <- numerator / denominator
exact_arch2

x <- na.omit(clean_data$prog1)
n <- length(x)
x_bar <- mean(x)
numerator <- sqrt(n) * sum((x - x_bar)^3)
denominator <- (sum((x - x_bar)^2))^(3/2)
exact_prog1 <- numerator / denominator
exact_prog1

x <- na.omit(clean_data$prog2)
n <- length(x)
x_bar <- mean(x)
numerator <- sqrt(n) * sum((x - x_bar)^3)
denominator <- (sum((x - x_bar)^2))^(3/2)
exact_prog2 <- numerator / denominator
exact_prog2

# Exact vs Pearson Values

paste("Arch1 - Pearson:", round(pearson_arch1, 2), "| Exact:", round(exact_arch1, 2))
paste("Arch2 - Pearson:", round(pearson_arch2, 2), "| Exact:", round(exact_arch2, 2))
paste("Prog1 - Pearson:", round(pearson_prog1, 2), "| Exact:", round(exact_prog1, 2))
paste("Prog2 - Pearson:", round(pearson_prog2, 2), "| Exact:", round(exact_prog2, 2))

# While Pearson's may be off by 0.08 to 0.29, it is still a reasonable approximation given time saved for minor to negligible errors.
```

## Part 2: Stem-and-Leaf Diagram v.s. Histogram

```{r}
# Set and clean genders
arch1_num    <- as.numeric(clean_data$arch1)
arch2_num    <- as.numeric(clean_data$arch2)
prog1_num    <- as.numeric(clean_data$prog1)
prog2_num    <- as.numeric(clean_data$prog2)
gender_clean <- trimws(tolower(clean_data$gender))

# Print stems
stem(na.omit(arch1_num[gender_clean == "m"]))
stem(na.omit(arch2_num[gender_clean == "m"]))
stem(na.omit(prog1_num[gender_clean == "m"]))
stem(na.omit(prog2_num[gender_clean == "m"]))
stem(na.omit(arch1_num[gender_clean == "f"]))
stem(na.omit(arch2_num[gender_clean == "f"]))
stem(na.omit(prog1_num[gender_clean == "f"]))
stem(na.omit(prog2_num[gender_clean == "f"]))


# Stem and leaf diagrams offer more accurate values for data points, while histograms generalize them into ranges thereby hiding exact distribution within intervals.
```

## Part 3: Box-Plot Analysis

```{r}
# Plot data points into box-plots

boxplot(arch1 ~ gender, data = clean_data, main = "Arch 1 Scores by Gender", col = c("blue", "purple"))

# For Arch 1 all students generally performed the same, though male students display a slightly higher median score then their counterparts.

boxplot(arch2 ~ gender, data = clean_data, main = "Arch 2 Scores by Gender", col = c("pink", "white"))

# Arch 2 reveals while both male and female students' median scores were roughly the same, male students generally performed better, with three outliers.

boxplot(prog1 ~ gender, data = clean_data, main = "Prog 1 Scores by Gender", col = c("green", "red"))

# Prog 1 shows results comparable to Arch 2's general performance but differs in that male students scored significantly higher medians than female students.

boxplot(prog2 ~ gender, data = clean_data, main = "Prog 2 Scores by Gender", col = c("yellow", "orange"))

#Finally, student performance in Prog 2 varies wildly across the distribution.
```
